name: myapp
description: A new Flutter project.

version: 1.6.9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_statusbarcolor: ^0.2.0
  html: ^0.14.0+1
  audioplayers: 
    git: git://github.com/danielR2001/audioplayers.git
  firebase_auth: ^0.11.1+7
  firebase_database: ^3.0.3
  dio: ^2.1.7 
  url_launcher: ^5.0.2
  permission_handler: ^3.1.0
  provider: ^3.0.0+1
  fluttertoast: ^3.1.0
  cupertino_icons: ^0.1.2
  auto_size_text: ^2.0.1
  flip_card: ^0.3.0
  marquee_widget: ^0.7.7
  connectivity: ^0.4.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:

  uses-material-design: true

  assets:
   - assets/images/default_playlist_image.jpg
   - assets/images/app_logo.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 400
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

